apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    name: nginx
    resources:
      limits:
        cpu: {{ .Values.resources.limits.cpu }}
        memory: {{ .Values.resources.limits.memory }}
